### ISSUE TITLE
docker-machine强制安装新版本docker

### ISSUE THREAD

**Issue by VFT** [AliyunContainerService/docker-machine-driver-aliyunecs#10]
@denverdino 你好，三天前重新下载了新版本的aliyunecs driver，发现docker的版本会强制安装成最新的1.12.0版本，即使指定engine-install-url参数也没起作用，原来的aliyunecs driver是正常的，这可能会是哪儿的情况？

**Comment by denverdino** [comment]
what is your engine-install-url parameter?

**Comment by VFT** [comment]
https://releases.rancher.com/install-docker/1.10.sh

**Comment by denverdino** [comment]
这部分没有修改的，检查一下是否参数传递正确

**Comment by twang2218** [comment]
@VFT 我没有办法重现你的问题，可否加上 `--debug` 参数然后把完整的调试信息贴过来看一下？

**Comment by VFT** [comment]
@twang2218 我的错，不是`aliyunecs driver`的问题，为了加快安装速度，所以在将docker提前安装到阿里镜像里边，然后又执行了yum update指令，结果就升级成最新版本了，忘记关闭issue了，抱歉

**Comment by dongzhenhua123456** [comment]
你好，我现在问题跟你一样，我也尝试了用nginx代理安装脚本.sh的问题，使用了上面的https://releases.rancher.com/install-docker/1.10.sh依然存在这个问题，我想问下你是怎么解决的，或者是怎么调式，我想看下安装的时候有没有走我的那个.sh的文件

**Comment by dongzhenhua123456** [comment]
我的engine-install-url是https://raw.githubusercontent.com/rancher/install-docker/master/17.03.2.sh或主机搭建的nginx的http://10.211.55.8:7777/依然存在这个问题
