### ISSUE TITLE
'InternetMaxBandwidthOut is not valid' error

### ISSUE THREAD

**Issue by nunchuk** [AliyunContainerService/docker-machine-driver-aliyunecs#12]
Hi there, the driver got a error
`InvalidParameter Message: The specified parameter "InternetMaxBandwidthOut" is not valid.` My guess is aliyun upgraded the api, the vpc network need to define `InternetMaxBandwidthOut = 0`. It's runs correctly in classic network.

**Comment by menglingwei** [comment]
now ,i fixed this bug。 update your code and try again.

**Comment by nunchuk** [comment]
Good job guys, I noticed that the program on drone was still no upgrade. Thx alot.

**Comment by menglingwei** [comment]
tell me program download link ? i check it

**Comment by nunchuk** [comment]
I typed incorrectly, this is the link [drone.io](https://drone.io/github.com/denverdino/machine/files)

**Comment by menglingwei** [comment]
sorry , download link is wrong . i updated it
