### ISSUE TITLE
Driver "aliyunecs" not found | on OSX

### ISSUE THREAD

**Issue by lsseckman** [AliyunContainerService/docker-machine-driver-aliyunecs#16]
Any ideas on this? Seems docker-machine can't find where I put the driver. Here's what I did:

`[05:54 PM | bin]$ ls`
`<other files> docker-machine-driver-aliyunecs.darwin-amd64	`

then check to see that it's in path:

```
[05:52 PM | ~]$ echo $PATH
/Users/etlab/anaconda/bin:/opt/boxen/heroku/bin:bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:node_modules/.bin:/opt/boxen/nodenv/shims:/opt/boxen/nodenv/bin:/opt/boxen/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/etlab/bin
```

then try to set up a new box with it: 

```
[05:47 PM | ~]$ docker-machine create -d aliyunecs 
```
```
Driver "aliyunecs" not found. Do you have the plugin binary accessible in your PATH?
```

edit: also referenced here -- https://develop.aliyun.com/command/docker

**Comment by lsseckman** [comment]
https://develop.aliyun.com/command/docker

**Comment by menglingwei** [comment]
sorry. help docs  'https://develop.aliyun.com/command/docker' will be updated tommorrow.
you can visite https://github.com/denverdino/docker-machine-driver-aliyunecs/blob/master/README.md

**Comment by menglingwei** [comment]
already updated!
