### ISSUE TITLE
macOs Sierra, $PATH incorrect 

### ISSUE THREAD

**Issue by davidbonachera** [AliyunContainerService/docker-machine-driver-aliyunecs#17]
Hi,

The binaries are located inside the folder /go/bin for me

So the command to add in our .bash_profile is :
```bash
export GOPATH=/Users/<Username>/go
export GOALIDRIV=$GOPATH/bin
export PATH="$GOALIDRIV:$GOPATH:$PATH"
```

**Comment by menglingwei** [comment]
i check it

**Comment by marcelwolf1989** [comment]
if you download the binary it is called `docker-machine-driver-aliyunecs.darwin-amd64`

to use it with docker-machine rename this to `docker-machine-driver-aliyunecs`and it can be found by docker-machine

**Comment by denverdino** [comment]
It should be put in the PATH
