### ISSUE TITLE
创建docker-machine失败， The specified instanceType beyond the permitted range

### ISSUE THREAD

**Issue by duruny** [AliyunContainerService/docker-machine-driver-aliyunecs#19]
docker-machine create -d aliyunecs --aliyunecs-tag provider=aliyuncos --aliyunecs-tag version=1.0 --aliyunecs-disk-size=20 --aliyunecs-io-optimized=optimized --aliyunecs-description=aliyunecs-machine-driver --aliyunecs-instance-type=ecs.t1.small --aliyunecs-access-key-id=<>--aliyunecs-access-key-secret=<> --aliyunecs-disk-category=cloud   --aliyunecs-region=cn-shenzhen --aliyunecs-ssh-password=<> default

创建docker-machine失败。

**Comment by denverdino** [comment]
应该是按量实例超过额度了，请开工单申请，多谢
