### ISSUE TITLE
Enable Public IP in VPC 

### ISSUE THREAD

**Issue by marcelwolf1989** [AliyunContainerService/docker-machine-driver-aliyunecs#23]
At the moment a elastic ip is tried to assign when using an VPC and no flag for private-ip only., which is not working  (See: https://github.com/AliyunContainerService/docker-machine-driver-aliyunecs/issues/22 ). 

The FAQ tells that an public ip is assigned automatically when the bandwidth is higher than 0.

```
How to purchase a VPC-type ECS with a PublicIP allocated? 
You can go to the ECS purchase page and select non-0Mbps for the internet bandwidth, and the system will automatically allocate a PublicIP. 
```

Link: https://www.alibabacloud.com/forum/read-581

The docker-machine-driver tries to allocate an Elastic IP. There should be a possibility to choose if public ip or elastic ip .

**Comment by denverdino** [comment]
export ECS_ACCESS_KEY_ID=xxxxx
export ECS_REGION=cn-beijing
export ECS_ACCESS_KEY_SECRET=xxxx
export MACHINE_DOCKER_INSTALL_URL=http://kubernetes.oss-cn-hangzhou.aliyuncs.com/docker_install.sh
export ENGINE_REGISTRY_MIRROR=https://registry.docker-cn.com
export ECS_VPC_ID=vpc-xxx
export ECS_VSWITCH_ID=vsw-xxx
docker-machine create -d aliyunecs test
