### ISSUE TITLE
我在使用专用网络的实例规格时得到了403的错误

### ISSUE THREAD

**Issue by 9ishell** [AliyunContainerService/docker-machine-driver-aliyunecs#25]

**Comment by denverdino** [comment]
更多信息？

**Comment by 9ishell** [comment]
Error creating machine: Error in driver during machine creation: seth-master | Failed to create instance: Aliyun API Error: RequestId: 7AF3251D-24C6-4BDC-AF6D-86E18FA9A741 Status Code: 403 Code: InvalidResourceType.NotSupported Message: This resource type is not supported; please try other resource types.
用的--aliyunecs-instance-type=ecs.t5-lc1m2.small报这个错，我加了--aliyunecs-vpc-id --aliyunecs-vswitch-id 仍然报错。
用的--aliyunecs-instance-type=ecs.n4.small没问题

**Comment by denverdino** [comment]
export ECS_ACCESS_KEY_ID=xxxxx
export ECS_REGION=cn-beijing
export ECS_ACCESS_KEY_SECRET=xxxx
export MACHINE_DOCKER_INSTALL_URL=http://kubernetes.oss-cn-hangzhou.aliyuncs.com/docker_install.sh
export ENGINE_REGISTRY_MIRROR=https://registry.docker-cn.com
export ECS_VPC_ID=vpc-xxx
export ECS_VSWITCH_ID=vsw-xxx
docker-machine create -d aliyunecs test

**Comment by denverdino** [comment]
InvalidResourceType.NotSupported 的意思是这个资源类型不被支持

**Comment by 9ishell** [comment]
<img width="1024" alt="wx20180415-154123 2x" src="https://user-images.githubusercontent.com/18731190/38776076-c82b2c88-40c3-11e8-91ab-68fa583a3b16.png">

**Comment by denverdino** [comment]
当前region不支持这个实例类型，你可以在控制台选择一个支持的实例类型
