### ISSUE TITLE
randomPassword generate invalid Password

### ISSUE THREAD

**Issue by dongqs** [AliyunContainerService/docker-machine-driver-aliyunecs#27]
https://github.com/AliyunContainerService/docker-machine-driver-aliyunecs/blob/3b8ab86f9375684aba64cc750037a28a5e52e77a/aliyunecs/utils.go#L35

randdomPasswrod generates weak password to cause errror like:

Error creating machine: Error in driver during machine creation: pass0 | Failed to create instance: Aliyun API Error: RequestId: xxxx Status Code: 400 Code: InvalidPassword.Malformed Message: The specified parameter "Password" is not valid.

**Comment by denverdino** [comment]
It is fixed in #28
