### ISSUE TITLE
windows版本如何安装？

### ISSUE THREAD

**Issue by ghost** [AliyunContainerService/docker-machine-driver-aliyunecs#29]
按照提示我已经配置了path的环境变量，但是还会提示
Driver "aliyunecs" not found. Do you have the plugin binary "docker-machine-driver-aliyunecs" accessible in your PATH?

**Comment by denverdino** [comment]
应该是没有找到相关的可执行文件  docker-machine-driver-aliyunecs.windows-amd64 这个文件和Docker Machine放到一起

**Comment by ghost** [comment]
我试试

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13448645/40721867-5ae5ffd8-644d-11e8-943c-42bc9ed0b32e.png)
还是不行，需要重启吗？

**Comment by ghost** [comment]
重启还是不行，算了我用linux安装了

**Comment by ghost** [comment]
这个问题纠结了1天了，死活不行，网上也没发现相同的问题，可能都是mac和linux安装的

**Comment by mijklgps** [comment]
我也遇到这个问题 +1
并且rename为docker-machine-driver-aliyunecs

**Comment by shidun** [comment]
我把 docker-machine-driver-aliyunecs 改成 docker-machine-driver-aliyunecs.exe 并且吧目录加到系统环 
境中 能执行了

**Comment by denverdino** [comment]
@menglingwei 麻烦补充帮助文档，多谢

**Comment by denverdino** [comment]
Fixed in #41
