### ISSUE TITLE
window10 把下载的文件放哪里？

### ISSUE THREAD

**Issue by hhcycj** [AliyunContainerService/docker-machine-driver-aliyunecs#32]
我用go get 安装不行，直接下载放到任意目录，把目录加到path也不行，该怎么弄？
win10下载后放什么目录下？要配置什么才行？

**Comment by hhcycj** [comment]
我用go build 生成exe文件可以用了，为什么提供windows下载的不是exe文件？

**Comment by mijklgps** [comment]
1---------------------------------------------------------
windows环境我自己试了那个文件不行
解决就是安装go语言环境
2---------------------------------------------------------
安装并配置go的环境变量
GOROOT=安装目录（bin的上一层）
GOPATH=自定义一个目录（不要使用安装目录）
3---------------------------------------------------------
然后加载go工程
go get github.com/AliyunContainerService/docker-machine-driver-aliyunecs
下载完毕在GOPATH目录下的bin里面有docker-machine-driver-aliyunecs.exe文件，配置该目录到环境变量，让pc识别该文件。
ps：aliyunecs=D:\\GOPATH\bin
然后 在path中添加 %aliyunecs%
4---------------------------------------------------------
运行一下以下命令已经显示ok
docker-machine create -d aliyunecs --help
5---------------------------------------------------------
意思就是自己编译源码，把docker-machine-driver-aliyunecs.exe添加到path，但是
官网提供的好像不行哎，哈哈哈。

**Comment by mijklgps** [comment]
> 我用go get 安装不行，直接下载放到任意目录，把目录加到path也不行，该怎么弄？
> win10下载后放什么目录下？要配置什么才行？

"go get" command need install go language

**Comment by denverdino** [comment]
下载完改个.exe文件，放到docker-machine所在的路径即可
