### ISSUE TITLE
创建docker host 虚机失败

### ISSUE THREAD

**Issue by shuaidetuowangsu** [AliyunContainerService/docker-machine-driver-aliyunecs#40]
执行的命令：docker-machine create -d aliyunecs --aliyunecs-io-optimized=optimized --aliyunecs-instance-type=ecs.g5.large --aliyunecs-access-key-id=xxx --aliyunecs-access-key-secret=xxxx  --aliyunecs-region=xxxx

Error creating machine: Error in driver during machine creation: docker-caoming | Failed to create instance: Aliyun API Error: RequestId: 98B3E02C-0F14-4AC7-944B-AA4DCE2B3D7A Status Code: 403 Code: InvalidResourceType.NotSupported Message: This resource type is not supported; please try other resource types.

**Comment by BSWANG** [comment]
@shuaidetuowangsu 看起来您指定的instance type在对应的region和可用区不存在或者没有库存，可以先在ECS控制台上看对应可用区可以创建什么样的机型再指定instance-type

**Comment by shuaidetuowangsu** [comment]
@BSWANG @denverdino 
是的，问题已解决，谢谢！
