### ISSUE TITLE
请问怎么添加指定资源组参数，默认是在默认组里

### ISSUE THREAD

**Issue by CN-Eden** [AliyunContainerService/docker-machine-driver-aliyunecs#45]
请问怎么添加指定资源组参数，默认是在默认组里

**Comment by menglingwei** [comment]
@CN-Eden 目前不支持该参数。我可以了解一下，您现在使用machine-driver 的场景是什么样的呢？

**Comment by CN-Eden** [comment]
> @CN-Eden 目前不支持该参数。我可以了解一下，您现在使用machine-driver 的场景是什么样的呢？

我现在的场景在阿里云平台是以资源组划分项目，在rancher上添加主机后，阿里云平台可以直接把这个主机添加到指定资源组里，这样我们方便统计资源组费用，间接统计项目消费资金

**Comment by menglingwei** [comment]
rancher使用的是 https://github.com/rancher/kontainer-engine-driver-aliyun 吧

**Comment by CN-Eden** [comment]
您好，我们rancher使用的是：https://github.com/rancher/ui-driver-skel，使用的是主机驱动

**Comment by menglingwei** [comment]
@CN-Eden  您有钉钉之类的嘛？

**Comment by CN-Eden** [comment]
有的，我的钉钉号：edenops

**Comment by menglingwei** [comment]
> edenops

好的。我加您

**Comment by menglingwei** [comment]
我已经更新了包。可以使用
docker-machine --debug create --driver aliyunecs --aliyunecs-resource-group-id=<ResourceGroupID>  <... 其他参数> <MachineName>
